version: 0.2.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: Fi0wCX6dAtIRMbXzE6Kq+f4xosR7rlAdq9Es534cctS5EkdGx3TVAyBQXHEINc8T
  skip_symbols: true
  on:
    appveyor_repo_tag: true
- provider: GitHub
  tag: ${appveyor_repo_tag_name}
  auth_token:
    secure: HO6RnnRv5dC7cWmb4hNtkoAr+oMRNjBcTAGISEHlZMdOUMY92Ri4lpVlk1So8UR9
  force_update: false
  on:
    appveyor_repo_tag: true