version: 0.1.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: D4KEeUOvvKD5JIK7stithmYwqeW92rTpiMyju/8H5uzpHG1543Q8tg7wvbnhb0d5
  skip_symbols: true
  on:
    appveyor_repo_tag: true
- provider: GitHub
  tag: ${appveyor_repo_tag_name}
  auth_token:
    secure: HO6RnnRv5dC7cWmb4hNtkoAr+oMRNjBcTAGISEHlZMdOUMY92Ri4lpVlk1So8UR9
  force_update: false
  on:
    appveyor_repo_tag: true